// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOkKEokqqMbZocBpK2iN0162OfZv2DdW4',
    appId: '1:888074809514:web:77fa63935f8385a2d560d3',
    messagingSenderId: '888074809514',
    projectId: 'todolistappz',
    authDomain: 'todolistappz.firebaseapp.com',
    storageBucket: 'todolistappz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYrqlGf_FhdHRFa1iJjgfZpeKeW0Jhlr4',
    appId: '1:888074809514:android:8e0e64db43119bd6d560d3',
    messagingSenderId: '888074809514',
    projectId: 'todolistappz',
    storageBucket: 'todolistappz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANNCdEIp8cXLbyW8bp1nPZzgBgtF7Ats8',
    appId: '1:888074809514:ios:03748f59d3cc3a60d560d3',
    messagingSenderId: '888074809514',
    projectId: 'todolistappz',
    storageBucket: 'todolistappz.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANNCdEIp8cXLbyW8bp1nPZzgBgtF7Ats8',
    appId: '1:888074809514:ios:03748f59d3cc3a60d560d3',
    messagingSenderId: '888074809514',
    projectId: 'todolistappz',
    storageBucket: 'todolistappz.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOkKEokqqMbZocBpK2iN0162OfZv2DdW4',
    appId: '1:888074809514:web:82022aa4db67a1a8d560d3',
    messagingSenderId: '888074809514',
    projectId: 'todolistappz',
    authDomain: 'todolistappz.firebaseapp.com',
    storageBucket: 'todolistappz.appspot.com',
  );
}
